### ISSUE TITLE
Add a simple window manager

### ISSUE THREAD

**Issue by nwrkbiz** [nwrkbiz/android-xserver#10]
Add a simple window manager which can be started optionally via a menu entry.

**Comment by foryoung2018** [comment]
@nwrkbiz can you sir provide the source code about this. I dont understand how to build this by ndk in android platform.
Do you get the code from this :https://flwm.sourceforge.net/? It dependency lib fltk? I dont really know hwo to complie it

**Comment by nwrkbiz** [comment]
@foryoung2018 

> @nwrkbiz can you sir provide the source code about this. I dont understand how to build this by ndk in android platform. Do you get the code from this :https://flwm.sourceforge.net/? It dependency lib fltk? I dont really know hwo to complie it

Yes the window manager is flwm from https://flwm.sourceforge.net/ and yes it depends on fltk. I do not use NDK, I create 100% statically linked binaries using a musl-based compiler.

I use this project to build all flwm (see unused_packages) and all dependencies: https://gitlab.com/nwrkbiz/static-build
