### ISSUE TITLE
X-server crashed every time 

### ISSUE THREAD

**Issue by Saikatsaha1996** [nwrkbiz/android-xserver#37]
I am trying to run X-server but i can't.. after 10 to 20 second getting crashed

![Screenshot_2023-01-15-10-05-51-715_au com darkside xdemo](https://user-images.githubusercontent.com/72664192/212523699-aee3e3e5-12ba-4b29-b558-00dadcd7af00.jpg)

**Comment by ZhymabekRoman** [comment]
Any logacat crash information?

**Comment by Saikatsaha1996** [comment]
> Any logacat crash information?

With normal llvmpipe GPU driver working
But my own GPU driver Wayland & x11 protocol GPU driver get crashed after launch 

How do I send?
I mean how do I create logcat?

I am opening like this

```
debian:~$export DISPLAY=:0
debian:~$dbus-launch --exit-with-session startxfce4
```

Found some error in terminal
```
(xfsettingsd:9930): Gdk-ERROR **: 05:46:20.601: The program 'xfsettingsd' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadImplementation (server does not implement operation)'.
  (Details: serial 114 error_code 17 request_code 35 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.
```

**Comment by nwrkbiz** [comment]
Are you able to provide the output of adb logcat?

**Comment by Saikatsaha1996** [comment]
> Are you able to provide the output of adb logcat?

I am just working with it.. just solved this problem..

It was crashed for Some buggy x11 GPU driver.. actually driver is under testing.. i will close issue after sometime..

**Comment by nwrkbiz** [comment]
Thanks!

**Comment by Saikatsaha1996** [comment]
> Thanks!

Nop dear! Thank you to you..
Problem solved
