### ISSUE TITLE
Many linux program can not lunch on this server

### ISSUE THREAD

**Issue by foryoung2018** [nwrkbiz/android-xserver#39]
chromium-browser
wps
vscode

and so on...

**Comment by ZhymabekRoman** [comment]
This is just basic implementation of X11 protocol. Feel free to PR.

Now I'm working on some fixes, but due to lack of knowledge it will be too slow.

---

My fork: https://github.com/ZhymabekRoman/android-xserver-enhanced

This fork contain these changes:

    X server doesn't restart on screen resolution changes - fixes #35 and #25
    Workaround fix for: Unsupported screen format: depth: 32, bits_per_pixel: 24, red_mask: ff0000, blue_mask: ff - fixes (almost) #30
    Gestures support:
        Zooming with fingers - !!! Some problems with handling events (idk whyyy)
        Three finger tap - hide/show navigation panel
        Four finger tap - Restore zoom

WIP:

    XKB
    Properly fix for #30

TODO:

    MIT SHM, SYNC, GLX extensions support - should fix #17 and #27

---

I will create PR after most of my planned features are done.

**Comment by foryoung2018** [comment]
@ZhymabekRoman Yes, I‘m doing the same. 
I am lack of knowledge also.  Another project xserver-xsdl can run many X program, but use native C code，and it's diffcult to work on.
This project is friendly to carry on, but I can't get the way to find out how to add more features. Even can't find out how to study details about xserver. X protocol is so loose, the gap between basic and fully function is so huge. 
Can you tell how to do this?
Many many thanks!!!

**Comment by ZhymabekRoman** [comment]
- Understanding X11 - https://magcius.github.io/xplain/article/index.html
- Official documentation: https://www.x.org/releases/X11R7.7/doc/
- Wikipedia - http://en.wikipedia.org/wiki/X_Window_System
- xlib documentation - https://www.tronche.com/gui/x/xlib/
- Understanding - X Window System, X Server, Xorg, Xfree86 - https://superuser.com/questions/145031/moving-from-windows-to-linux-understanding-x-window-system-x-server-xorg | https://gist.github.com/makeittotop/fb77a2cee0a1fe1707cb

Require translator:
- (In Russian) Understanding basics of X11 protocol in the lowest level  - https://habr.com/ru/articles/712376/
- (In Russian) Network connection in X11 - https://habr.com/ru/companies/ruvds/articles/574742/
- (In Russian) How graphical stack works in Linux - https://habr.com/ru/articles/148954/
- (In Russian) ...after X Windows protocol - https://habr.com/ru/articles/321470/

**Comment by nwrkbiz** [comment]
@foryoung2018  https://www.x.org/releases/X11R7.7/doc/xproto/x11protocol.pdf

The protocol specification starts at page 140.
